
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.0alpha2'
version_full = 'aa6a34bc4ac5962dacaa5908778e444fe5aae3d7'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
