#!/usr/bin/env python
import os
import sys
import netrc
import argparse
from leap.soledad.common.couch import CouchDatabase
from leap.soledad.common.couch import is_db_name_valid


description = """
Creates a user database.
This is meant to be used by Soledad Server.
"""
parser = argparse.ArgumentParser(description=description)
parser.add_argument('dbname', metavar='user-d34db33f', type=str,
               help='database name on the format user-{uuid4}')
NETRC_PATH = '/etc/couchdb/couchdb-admin.netrc'


def url_for_db(dbname):
    if not os.path.exists(NETRC_PATH):
        print ('netrc not found in %s' % NETRC_PATH)
        sys.exit(1)
    parsed_netrc = netrc.netrc(NETRC_PATH)
    host, (login, _, password) = parsed_netrc.hosts.items()[0]
    url = ('http://%(login)s:%(password)s@%(host)s:5984/%(dbname)s' % {
           'login':login,
           'password':password,
           'host':host,
           'dbname':dbname})
    return url


if __name__ == '__main__':
    args = parser.parse_args()
    if not is_db_name_valid(args.dbname):
        print ("Invalid name! %s" % args.dbname)
        sys.exit(1)
    url = url_for_db(args.dbname)
    db = CouchDatabase.open_database(url=url, create=True,
                                     replica_uid=None, ensure_ddocs=True)
    print ('success! Created %s, replica_uid: %s' % (db._dbname, db.replica_uid))
