
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "91cbf6c084569a24c4186f3ff745448d3c51756a",
 "version": "0.8.0"
}
'''  # END VERSION_JSON

def get_versions():
    return json.loads(version_json)
