
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.4'
version_full = '49fd07cde3b1f50dcce85d4e9fcdfc6196f484c4'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
