
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = 'fd2a9adfc9148e47b85add78d8f3c981e4fad885'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
