#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin


PIDFILE=/var/run/soledad.pid
RUNDIR=/var/lib/soledad/
OBJ=leap.soledad.server.application
LOGFILE=/var/log/soledad.log
HTTPS_PORT=2424
PLAIN_PORT=65534
CERT_PATH=/etc/leap/soledad-server.pem
PRIVKEY_PATH=/etc/leap/soledad-server.pem

[ -r /etc/default/soledad ] && . /etc/default/soledad

test -r /etc/leap/ || exit 0

. /lib/lsb/init-functions


case "$1" in
    start)
        echo -n "Starting soledad: twistd"
        HOME="/var/lib/soledad/" \
          start-stop-daemon --start --quiet --exec /usr/local/bin/twistd -- \
                          --pidfile=$PIDFILE \
                          --logfile=$LOGFILE \
                          web \
                          --wsgi=$OBJ \
                          --https=$HTTPS_PORT \
                          --certificate=$CERT_PATH \
                          --privkey=$PRIVKEY_PATH \
                          --port=$PLAIN_PORT
        echo "."
    ;;

    stop)
        echo -n "Stopping soledad: twistd"
        start-stop-daemon --stop --quiet  \
            --pidfile $PIDFILE
        echo "."
    ;;

    restart)
        $0 stop
        $0 start
    ;;

    force-reload)
        $0 restart
    ;;

    status)
        status_of_proc -p $PIDFILE /usr/local/bin/twistd soledad && exit 0 || exit $?
    ;;

    *)
        echo "Usage: /etc/init.d/soledad {start|stop|restart|force-reload|status}" >&2
        exit 1
    ;;
esac

exit 0
